version: 2

multi-ecosystem-groups:
  semantix-routine:
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Etc/UTC

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /backend
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /frontend
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: pip
    directory: /backend
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: pip
    directory: /sdk/python
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: npm
    directory: /frontend
    patterns:
      - "*"
    multi-ecosystem-group: semantix-routine
    rebase-strategy: disabled
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
