resolver 127.0.0.11 valid=5s ipv6=off;

upstream semantix_backend {
    zone semantix_backend 64k;
    server backend-a:8000 resolve max_fails=1 fail_timeout=5s;
    server backend-b:8000 resolve max_fails=1 fail_timeout=5s;
}
