"""Share package semantic limits while owning server preview/evaluation defaults.

The four imported semantic limits are the existing __all__ re-exports.
Remaining constants supply server preview and evaluation configuration/schema
bounds; their enforcement belongs to the consuming settings and validators.
"""

from semantix_cache._semantics import (
    MAX_MEMORY_CACHE_SIZE,
    MAX_PROMPT_LENGTH,
    MAX_REQUEST_CACHE_TTL_SECONDS,
    MAX_RESPONSE_LENGTH,
)

__all__ = [
    "MAX_MEMORY_CACHE_SIZE",
    "MAX_PROMPT_LENGTH",
    "MAX_REQUEST_CACHE_TTL_SECONDS",
    "MAX_RESPONSE_LENGTH",
]

MAX_RESPONSE_PREVIEW_LENGTH = 240

DEFAULT_EVALUATION_DATASET_MAX_CASES = 50
DEFAULT_EVALUATION_DATASET_MAX_DECODED_BYTES = 49_152
DEFAULT_EVALUATION_MAX_WORKLOAD_QUERIES = 250
DEFAULT_EVALUATION_DATASET_MAX_PERSISTED_PER_NAMESPACE = 100
DEFAULT_EVALUATION_DATASET_DEFAULT_RETENTION_DAYS = 30
DEFAULT_EVALUATION_DATASET_MAX_RETENTION_DAYS = 365
DEFAULT_EVALUATION_DATASET_CLEANUP_BATCH_SIZE = 100

MAX_EVALUATION_DATASET_NAME_LENGTH = 100
MAX_EVALUATION_DATASET_DESCRIPTION_LENGTH = 300
MAX_EVALUATION_CASE_ID_LENGTH = 100
MAX_EVALUATION_CATEGORY_LENGTH = 100
MAX_EVALUATION_NOTE_LENGTH = 500
